version: '3.9'

services:
  postgres:
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=realworld
      - POSTGRES_PASSWORD=realworld
      - POSTGRES_DB=realworld
